version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - DB_USER=postgres
      - DB_PASSWORD=3214
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=expense_tracker
      - JWT_SECRET=133456
      - PORT=5000
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - ./uploads:/app/uploads
    command: ["npm", "run", "dev"]

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:5000
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=3214
      - POSTGRES_DB=expense_tracker
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
